### PR TITLE
Josh dev

### PR DESCRIPTION
**Pull request by JoshuaWarejko**
Finally got this working... I think something was wrong with the documents that I already had in my local DB for some reason. 
**Note**: The error messages for the endpoints changed for some reason so that on the frontend you get the message in error.error instead of error.message. I am not at all sure why this happened because I didn't change the responses in the /join or /register routes. I went through and changed the frontend to accommodate this change.

### CODE REVIEW

**Comment by torch2424** [comment]
So this is ready to go? 😄

**Comment by JoshuaWarejko** [comment]
@torch2424 Yeah, should be good now. Just added one more to check to make sure email isn't already taken.

**Comment by torch2424** [comment]
Forsure, Do you mind if I pull this in after the demo? Just to be safe? :)

**Comment by JoshuaWarejko** [comment]
@torch2424 I kind of wanted it for the demo, that is why I was rushing to finish it yesterday haha but if you aren't feeling it, no worries 👍

**Pull request merged**
